Update Simple Icons To Latest Versions Using Actions
mackenly/simple-icons-stream-deck pull request #5
Opened 2023-11-26 23:25 UTC by mackenly

Closes #4 

This PR adds a GitHub Action to create the latest release every week from the main simple icons repo.

2023-11-27 16:53 UTC, mondeja reviewed
Hi, maintainer of simple-icons here :wave: I'll provide some help if you don't mind to create the release workflow.

2023-11-27 18:39 UTC, mackenly commented on .github/workflows/release.yml
> +                echo "::set-output name=NEW_VERSION::${VER[0]}.${VER[1]}.${VER[2]}"
Hi, thank you for the feedback. This is very much a draft, but thank you for the feedback, especially on the depreciated command.

2023-11-27 23:13 UTC, mackenly commented
The API endpoint for simple icons releases doesn't seem to include assets. https://api.github.com/repos/simple-icons/simple-icons/releases/latest Going to just download a zip of the master branch instead.

2023-11-28 06:18 UTC, mondeja commented
> The API endpoint for simple icons releases doesn't seem to include assets. https://api.github.com/repos/simple-icons/simple-icons/releases/latest Going to just download a zip of the master branch instead.

You can download by version from tags using the url `https://github.com/simple-icons/simple-icons/archive/refs/tags/{version}.zip` or you can get the tarball and zipball urls from the endpoint that you've provided querying `tarball_url` and `zipball_url` fields.

2023-11-28 18:03 UTC, mackenly commented
@mondeja  That's a much better approach, thanks! 🎉
Do you have any experience with permission errors when running Python scripts in actions? I've been unable to figure out how to give it permission to add, edit, and delete files. I've [opened a discussion here](https://github.com/orgs/community/discussions/77227) with more details and logs.

2023-11-28 19:05 UTC, mondeja commented
> @mondeja That's a much better approach, thanks! 🎉 Do you have any experience with permission errors when running Python scripts in actions? I've been unable to figure out how to give it permission to add, edit, and delete files. I've [opened a discussion here](https://github.com/orgs/community/discussions/77227) with more details and logs.

Try `os.chmod(file, stat.S_IWRITE)`

2023-11-29 04:44 UTC, mackenly commented
@mondeja The permissions error ended up being because I was running the script from the wrong directory using `python script/main.py`. Since the script navigates between the folders using `os.getcwd()` it wasn't able to replace the `script` from the path and was trying to delete/edit/create files that didn't exist. 

This should be ready to go. I've removed the on push trigger leaving just the cron and dispatch so there aren't any releases currently published. If there's nothing special that needs to be done as far as simple-icons, I'll merge and run it manually for this release just to make sure it works right on `main`. Thank you for your help!

2023-11-29 05:07 UTC, mondeja requested changes
Thanks for your work. Just a minor change...

2023-11-29 05:07 UTC, mondeja commented on .github/workflows/release.yml
> +                cd ..
The working directory is not preserved between steps. Also, you can use [`working-directory`](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepsworking-directory):

```suggestion
              working-directory: scripts
              run: python main.py ./../simple-icons-${{ needs.version.outputs.LATEST_TAG_NAME }}/simple-icons-${{ needs.version.outputs.LATEST_TAG_NAME }} ${{ needs.version.outputs.LATEST_TAG_NAME }}
```

2023-11-29 05:12 UTC, mondeja approved these changes
Great! 🥇

I'll update the simple-icons version using this package on the dynamic badge of the [simple-icons README](https://github.com/simple-icons/simple-icons#third-party-extensions).

2023-11-29 05:13 UTC, merged

2023-11-29 05:19 UTC, mondeja commented
Ups, seems that the directory is `script/`, not `scripts/` 😅

2023-11-29 05:23 UTC, mackenly commented
All good. Btw the PR you linked is on Blazor, but this one is for Stream Deck.

Release successfully created: [https://github.com/mackenly/simple-icons-stream-deck/releases](https://github.com/mackenly/simple-icons-stream-deck/releases)